"""YAML configuration loading and merging for handoff.

Configuration is split into two layers:

  1. Mechanism (cli/backend_types.yaml) — HOW each backend type is launched
     (command, PTY, flag templates).  Bundled with the package; NOT overridable
     by user config.  This is the program's behavioural contract.

  2. Data (~/.handoff/config.yaml) — user-owned backends, models, env vars.
     Generated by `handoff init` from the bundled template; the sole source of
     backend definitions.  No hidden merge layers — what you see is what runs.

Backend resolution:
  - Resolved backend = types[<type>] (mechanism) + the backend's own fields (data)
  - Deep-merge for mappings; lists are replaced wholesale (not concatenated)
  - The first backend in the user config is the default (dict insertion order).
"""

from __future__ import annotations

import os
import re
import sys
import copy
from typing import Optional

try:
    import yaml
except ImportError:
    print(
        "handoff: PyYAML is required. Install it with: pip install pyyaml",
        file=sys.stderr,
    )
    sys.exit(1)

_BACKEND_TYPES_PATH = os.path.join(os.path.dirname(__file__), "backend_types.yaml")
_USER_CONFIG_TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "user_config_template.yaml")

# Top-level config keys that belong to the mechanism layer or are otherwise
# removed.  Warn once and ignore.  system_prompt is deliberately absent from
# this list — users CAN override it.
_DEPRECATED_KEYS = (
    "type_defaults", "backend_types", "backend_template",
    "fast_backend", "default_model", "pro_model", "default_backend",
)

_TEMPLATE_URL = "https://github.com/dazuiba/handoff/blob/main/cli/user_config_template.yaml"


def user_config_dir() -> str:
    return os.path.join(os.path.expanduser("~"), ".handoff")


def user_config_path() -> str:
    return os.path.join(user_config_dir(), "config.yaml")


def _load_yaml(path: str) -> dict:
    """Load a YAML file, returning an empty dict if not found."""
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r") as f:
            data = yaml.safe_load(f) or {}
        if not isinstance(data, dict):
            print(f"handoff: config {path} must be a mapping", file=sys.stderr)
            sys.exit(1)
        return data
    except yaml.YAMLError as e:
        print(f"handoff: error parsing {path}: {e}", file=sys.stderr)
        sys.exit(1)


def write_default_user_config() -> bool:
    """Copy the bundled template to ~/.handoff/config.yaml if missing.
    Return True when written.
    """
    path = user_config_path()
    if os.path.isfile(path):
        return False

    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(_USER_CONFIG_TEMPLATE_PATH, "r") as src:
            content = src.read()
        with open(path, "w") as dst:
            dst.write(content)
        return True
    except OSError as e:
        print(f"handoff: failed to create default user config at {path}: {e}", file=sys.stderr)
        sys.exit(1)


def _ensure_user_config_exists():
    if os.path.isfile(user_config_path()):
        return

    from .commands.init import run_init

    run_init()
    if not os.path.isfile(user_config_path()):
        print(f"handoff: initialization did not create {user_config_path()}", file=sys.stderr)
        sys.exit(1)


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge override into base, return new dict."""
    result = copy.deepcopy(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = copy.deepcopy(val)
    return result


_ENV_VAR_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def _expand_env_vars(value):
    """Recursively expand ${ENV_VAR} references in config string values.

    Unset variables expand to the empty string (later caught by
    ensure_backend_token_ready when a real token is required).
    """
    if isinstance(value, str):
        return _ENV_VAR_RE.sub(lambda m: os.environ.get(m.group(1), ""), value)
    if isinstance(value, dict):
        return {k: _expand_env_vars(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_expand_env_vars(v) for v in value]
    return value


def _resolve_include_path(include_val: str, including_file_dir: str) -> str:
    """Resolve an include path.

    Absolute paths are used as-is.
    Relative paths: first try relative to the including file's directory,
    then fall back to the package directory.
    """
    if os.path.isabs(include_val):
        return include_val

    # Try relative to the including file's directory first
    candidate = os.path.join(including_file_dir, include_val)
    if os.path.isfile(candidate):
        return candidate

    # Fall back to the package directory
    candidate = os.path.join(os.path.dirname(__file__), include_val)
    if os.path.isfile(candidate):
        return candidate

    return candidate


def _load_with_includes(path: str, _seen: Optional[set] = None) -> dict:
    """Load a YAML file, recursively resolving `include:` directives.

    `include` can be a string (single path) or list of paths.
    Included files are deep-merged first (in order), then the current
    file's own keys are deep-merged on top so they override includes.

    Absolute include paths are used as-is.  Relative paths are resolved
    against the including file's directory first, then the package dir.

    _seen tracks already-visited paths to guard against cycles.
    """
    if _seen is None:
        _seen = set()

    real = os.path.realpath(path)
    if real in _seen:
        return {}
    _seen.add(real)

    data = _load_yaml(path)
    includes = data.pop("include", None)
    if isinstance(includes, str):
        includes = [includes]
    elif includes is None:
        includes = []

    including_dir = os.path.dirname(path)

    # Deep-merge all includes first
    merged = {}
    for inc in includes:
        inc_path = _resolve_include_path(inc, including_dir)
        if os.path.isfile(inc_path):
            inc_data = _load_with_includes(inc_path, _seen)
            merged = _deep_merge(merged, inc_data)

    # Then deep-merge current file's own keys on top
    merged = _deep_merge(merged, data)

    return merged


class Config:
    """Resolved handoff configuration.

    Mechanism (backend_types.yaml) + Data (~/.handoff/config.yaml).
    The two layers are loaded independently; user config CANNOT override the
    mechanism layer (flags, PTY).  Backend resolution deep-merges the
    mechanism fields for the backend's type with the user's backend fields.
    """

    def __init__(self):
        _ensure_user_config_exists()

        # Mechanism layer — how each type is launched (NOT overridable).
        self._backend_types = _load_yaml(_BACKEND_TYPES_PATH)
        types = self._backend_types.get("types")
        if not isinstance(types, dict) or not types:
            print(
                f"handoff: missing or invalid types in {_BACKEND_TYPES_PATH}",
                file=sys.stderr,
            )
            sys.exit(1)

        # Data layer — user's backends (sole source of backend definitions).
        self._user = _load_with_includes(user_config_path())
        self._warn_deprecated()
        self._validate()

    # ── public read-only helpers ──────────────────────────────────────────────

    @property
    def user_config_path(self) -> str:
        return user_config_path()

    @property
    def backend_types_path(self) -> str:
        return _BACKEND_TYPES_PATH

    @property
    def default_backend(self) -> str:
        """The default backend: first entry in the user config (insertion order)."""
        backends = self._user.get("backends", {})
        if isinstance(backends, dict) and backends:
            return next(iter(backends))
        print("handoff: no backends configured", file=sys.stderr)
        sys.exit(1)

    @property
    def system_prompt(self) -> str:
        """User's system_prompt if set, otherwise the built-in default."""
        user_sp = self._user.get("system_prompt")
        if user_sp is not None:
            return user_sp
        return self._backend_types.get("system_prompt", "")

    @property
    def type_defaults(self) -> dict:
        """Mechanism-layer type definitions (command, pty, flags). Read-only."""
        return copy.deepcopy(self._backend_types.get("types", {}))

    @property
    def backends(self) -> dict:
        """Return the resolved backends dict.

        Resolution per backend: types[<type>] mechanism fields -> backend's own
        fields from user config (deep merge; lists replaced wholesale). String
        values get ${ENV_VAR} interpolation.

        Every resolved backend carries a `type` key (defaults to "claude" when
        omitted).
        """
        raw = self._user.get("backends", {})
        if not isinstance(raw, dict):
            print("handoff: config key 'backends' must be a mapping", file=sys.stderr)
            sys.exit(1)

        types = self._backend_types.get("types", {}) or {}
        result = {}
        for name, overrides in raw.items():
            if not isinstance(overrides, dict):
                print(f"handoff: backend '{name}' must be a mapping", file=sys.stderr)
                sys.exit(1)
            btype = overrides.get("type", "claude")
            base = types.get(btype)
            if not isinstance(base, dict):
                base = {}
            merged = _deep_merge(base, overrides)
            merged["type"] = btype
            result[name] = _expand_env_vars(merged)
        return result

    def get_backend(self, name: str) -> Optional[dict]:
        """Resolve a named backend (returns deep-copied merged dict or None)."""
        backends = self.backends  # already merged with type mechanism
        return copy.deepcopy(backends.get(name))

    def get_config_paths(self) -> list[str]:
        """Return paths of all config source files (for mtime checks)."""
        paths = [_BACKEND_TYPES_PATH]
        uc = user_config_path()
        if os.path.isfile(uc):
            paths.append(uc)
        return paths

    # ── validation ────────────────────────────────────────────────────────────

    def _warn_deprecated(self):
        """Warn about (and drop) top-level keys that belong to the mechanism
        layer or are otherwise removed.  system_prompt is deliberately kept —
        users can override it.
        """
        for key in _DEPRECATED_KEYS:
            if key in self._user:
                print(
                    f"handoff: config key '{key}' is deprecated and was ignored "
                    f"(the mechanism layer is now in backend_types.yaml; "
                    f"backends carry their own model/pro_model fields)",
                    file=sys.stderr,
                )
                self._user.pop(key, None)

    def _validate(self):
        backends = self._user.get("backends", {})
        if not isinstance(backends, dict) or not backends:
            print(
                "handoff: no backends configured. "
                f"See {_TEMPLATE_URL} for the default template.",
                file=sys.stderr,
            )
            sys.exit(1)

        types = self._backend_types.get("types", {})
        known_types = list(types.keys()) if isinstance(types, dict) else []

        for name, overrides in backends.items():
            if not isinstance(overrides, dict):
                continue  # reported when resolving
            btype = overrides.get("type", "claude")
            if btype not in types:
                print(
                    f"handoff: backend '{name}' has unknown type '{btype}' "
                    f"(known: {', '.join(sorted(known_types))})",
                    file=sys.stderr,
                )
                sys.exit(1)
            if btype == "claude" and not overrides.get("model"):
                print(
                    f"handoff: backend '{name}' (type claude) must have a 'model' field. "
                    f"See {_TEMPLATE_URL} for the default template.",
                    file=sys.stderr,
                )
                sys.exit(1)
